USE chores_db;

CREATE TABLE users
(
    id INT NOT NULL AUTO_INCREMENT ,
    name varchar(255) NOT NULL ,
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ,
  	UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ,
    
    PRIMARY KEY (id)
);


-- INSERT INTO users (name) VALUES ("justin");
-- INSERT INTO users (name) VALUES ("james");